databases:
  - name: vastrasagar-db
    plan: free
    databaseName: vastrasagar
    user: vastrasagar_user

services:
  - type: web
    name: vastrasagar
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vastrasagar-db
          property: connectionURI
      - key: FLASK_ENV
        value: production
